/*  layout: an object-oriented Javascript library, version 1.0.0
 *  (c) 2005 DeepThink <jed.zhu@deepthink.com.au>
 *
 *  THIS FILE IS AUTOMATICALLY GENERATED. When sending patches, please diff
 *  against the source tree, available from the layout darcs repository. 
 *
 *  layout is freely distributable under the terms of an MIT-style license.
 *
 *  For details, see the layout.js web site: http://deepthink.com.au/
 *
/*--------------------------------------------------------------------------*/
var XmlHttp = false;

var ipSearch = null;

var metas = null;

var ie=(document.all)?true:false;

function getParams(metaMethod,metaParams)
{
    var reParams = new String();
    var temParams = new String();
    var strArray  = new String();
    
    //alert(metaParams);
    var strParams = metaParams.toString().split("|");
    
    if(strParams[0].length != 0)
    {
        for(var i = 0; i < strParams.length;i++)
        {
            try
            {
               // alert(strParams[i].toString());
                if(isdigit(strParams[i]))
                {
                    temParams += "|" + strParams[i].toString();
                    break;
                }
                if(strParams[i].toString() == "downloaduuid")
                {
                    temParams += "|" +downloaduuid.toString();
                    break;
                }
                if(strParams[i].toString() == "uploaduuid")
                {
                    temParams += "|" +uploaduuid.toString();
                    break;
                }
                if(strParams[i].toString() == "regionid")
                {
                    temParams += "|" + getAddressValue("RegionID");
                    continue;
                }
                if(strParams[i].toString() == "uploadfilepath")
                {
                    temParams += "|" + uploadpath;
                    break;
                }
                if(strParams[i].toString() == "regionname")
                {
                    //alert(getAddressValue("RegionName"));
                    temParams += "|" + getAddressValue("RegionName");
                    break;
                }
                if(strParams[i].toString() == "regionsave")
                {
                    temParams += "|" + "D:\\downloads\\terrain\\"+getAddressValue("RegionID")+".r32";
                    break;
                }
				if(strParams[i].toString() == "avatar_name")
				{
					temParams += "&avatar_name=" + document.forms["form1"].elements[strParams[i]].value;
					continue;
				}
			    if(strParams[i].toString() == "password")
				{
					temParams += "&password=" + document.forms["form1"].elements[strParams[i]].value;
					continue;
				}
				if(strParams[i].toString() == "verifynumber")
				{
					temParams += "&verifynumber=" + document.forms["form1"].elements[strParams[i]].value;
					continue;
				}
				if(strParams[i].toString() == "useruri")
				{
				    //var str = metaParams.toString().split("|");
					temParams += "&seruri=" + document.forms["form1"].elements["useruri"].options[document.forms["form1"].elements["useruri"].selectedIndex].text.toString();
					
					continue;
				}
				if(strParams[i].toString() == "seruri")
				{
					temParams += "&seruris=" + document.forms["form1"].elements["seruri"].options[document.forms["form1"].elements["seruri"].selectedIndex].text.toString();
					continue;
				}
				if(strParams[i].toString()== "startTime")
				{
				    temParams += "&startTime=" + document.forms["form1"].elements[strParams[i]].value;  //+ "-" +document.forms["form1"].elements["starthour"].options[document.forms["form1"].elements["starthour"].selectedIndex].text.toString() +"-"+ document.forms["form1"].elements["startmin"].options[document.forms["form1"].elements["startmin"].selectedIndex].text.toString()+"-"+document.forms["form1"].elements["startsec"].options[document.forms["form1"].elements["startsec"].selectedIndex].text.toString();
				    continue;
				}
			    if(strParams[i].toString() == "endTime")
				{
				    temParams += "&endTime=" + document.forms["form1"].elements[strParams[i]].value;  //+ "-" +document.forms["form1"].elements["endhour"].options[document.forms["form1"].elements["endhour"].selectedIndex].text.toString() +"-" + document.forms["form1"].elements["endmin"].options[document.forms["form1"].elements["endmin"].selectedIndex].text.toString()+"-"+document.forms["form1"].elements["endsec"].options[document.forms["form1"].elements["endsec"].selectedIndex].text.toString();
				    continue;
				}
			
                strArray = document.forms["form1"].elements[strParams[i]].value;
        
               
                temParams += "|"+strArray;
            }
            catch(failed)
            {
                try
                {
                    strArray = (ie)?document.all[strParams[i].toString()].innerHTML : document.getElementsById(strParams[i].toString()).innerHTML;
                    
                    temParams += "|"+strArray;
                }
                catch(failed)
                {
                    temParams += "|" + strParams[i].toString();
                }
            }
            
        }
    }

    
    //alert(reParams);
    //reParams += "&q=" + ipSearch + "|" +metaMethod +temParams;
	if(metaMethod == "login" || metaMethod == "get_user_by_name" )
	{
		reParams += "&method=" +metaMethod + temParams;
	}
	else if ( metaMethod == "WebGetTransaction")
	{
	    reParams += "&method=" +metaMethod + temParams + "&seruris=&userID=&lastIndex=-1";
	}
	else if (metaMethod == "WebGetTransactionNum")
	{
	    reParams += "&method=" +metaMethod + temParams + "&seruris=&userID=";
	}
	else
	{
		reParams += "&method=" +metaMethod + "&parms=" + temParams;
	}
    
    return reParams;
    
    
}
function FillLayout()
{
    if(XmlHttp.readyState == 4)
    {
        if(XmlHttp.status == 200)
        {
            //alert(XmlHttp.responseText);
            
            var xmlDoc = XmlHttp.responseXML.documentElement; 

            var xSel = xmlDoc.getElementsByTagName('selectElement')[0]; 
                        
            var strEName = xSel.childNodes[0].firstChild.nodeValue;   
            //alert(strEName + " element");                                        
                                        
            var strFName = xSel.childNodes[1].firstChild.nodeValue;
            //alert(strFName + " form");   
                                                                             
            var objDDL = document.forms[strFName].elements[strEName];
            
            var xMod = xmlDoc.getElementsByTagName('selectElement')[1]; 
                        
            var strMethod = xMod.childNodes[1].firstChild.nodeValue;   
            //alert(strMethod + "  method");                                        
                                        
            var strState = xMod.childNodes[0].firstChild.nodeValue;   
            //alert(strState + "  success");
             
            var xRows = xmlDoc.getElementsByTagName('entry')[0];  
           // alert( xRows[0].innerHTML);
          
            switch(strMethod)
            {
                case "GetRegionIDandNames":
                    {
                        createRegionTable(xRows,strState);
                        break;
                    }   
                case "DownLoadTerrain":
                case "DownLoadOAR":
                    {
                        downLoadHandler(objDDL,xRows,strState,strEName);
                        break; 
                    }
                case "TerrainSource":
                case "OARSource":
                    {
                        checkDownLoadState(xRows,strState);
                        break;
                    }
                 case "UpLoadTerrain":
                 case "UpLoadOAR":
                    {
                        //alert(strMethod+strState);
                        checkUpLoadState(xRows,strMethod,strState);
                        break;
                    }  
				case "get_user_by_name":
					{
						//alert("success");
						loginhandler(xRows,strState);
						
						
					    break;
					}
				case "WebLogin":
					{
					   // alert("weblogin");
					    WebLogin(xRows,strState,strMethod);
					    break;
					}
				case "WebGetTransaction":
					{
					   // alert("gettransaction");
					   // closeDiv("load");
					    WebGetTransaction(xRows,strState,strMethod);
					    break;
					}
				case "WebGetTransactionNum":
				    {
				      
				        WebGetTransactionNum(xRows,strState,strMethod);
					    break;
				    }
				case "WebGetBalance":
				    {
				        WebGetBalance(xRows,strState,strMethod);
				        break;
				    }
				case "LoadcurrentPage":
				  {
				    
    				        WebGetTransaction(xRows,strState,strMethod);
				        break;
				    }
				 case "Logoff":
				    {
				    
				    WebLogoff(xRows,strState,strMethod);
				    break;
				    }
				    case "onload":
				    {
				    Webonload(xRows,strState,strMethod);
				    break;
				    }
				    case "queryTransaction":
				    {
				    QueryLoad(xRows,strState,strMethod);
				    break;
				    }
                 default:
                    {     
                        checkStateInfo(xRows,strState);
                        
                        break;
                    }    

                               
                
            }
            
            
     
        }
    }
}
function GetURL()
{
    var URL = new String();
    
    var RowURL = new String();
    
    try
    {
        RowURL = document.forms["form1"].elements["admin_query_region"].options[document.forms["form1"].elements["admin_query_region"].selectedIndex].text.toString();
    }
    catch(failed)
    {
        RowURL = getAddressValue("RegionIP");
    }
    
    URL = "http://" + RowURL +":9000";
    
    return URL;
}
function reloadcode(){ 
document.getElementById('cknimg').src = "VerifyCode.aspx?";
} 
function FillTerritory(oElem,oTarget,callback,method,uri)
{

    if(!uri)
        uri = "MoneyMonitor.aspx";
    //alert(uri);
       // alert(oTarget.name);
    var strParams = "form=" + oTarget.form.name + "&target=" + oTarget.name;
    
   // alert(strParams);
    
    if(metas == null)   metas = document.getElementsByTagName("meta");
        
    var strContent = new String();
        
    var strElemName = null;
    if(oTarget.name == "TerrainEffects"||oTarget.name == "TerrainModification")
    {
        strElemName = oElem.text.toString();
    }
    else
    {
        strElemName =  String(oElem.name);
    }
    
        
    for(var ix = 0; ix < metas.length;ix++)
    {
        if(metas[ix].name == strElemName)
        {
            strContent = metas[ix].content.toString();
            
            strParams += getParams(strElemName,strContent);
                  
            break;
        }
    }
  // alert(strParams);
   ContentLoader(uri,callback,method,strParams);  
      
}


function ContentLoader(url,callback,method,strParams,contentType)
{
  if (!method)
      method="GET";
  if (!contentType && method=="POST")
  {
      contentType = "application/x-www-form-urlencoded";
  }

  if (window.ActiveXObject)
  {
      var iex = new Array("MSXML2.XMLHTTP.5.0","MSXML2.XMLHTTP.4.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP4","Microsoft.XMLHTTP");
      for(var i = 0; i < iex.length;i++)
      {
        try
        {
            XmlHttp = new ActiveXObject(iex[i]);    
            if(XmlHttp)
                break;
    
        }
        catch(failed)
        {
           // alert(failed.name + ":" + failed.message);
        }
      }
  }
  if(!XmlHttp && window.XMLHttpRequest)
  {
      XmlHttp = new XMLHttpRequest();
      
  }
  if(!XmlHttp)
        alert("Error : Initializing XMLHttpRequest Failed!");
  else
  {
      if(contentType)
      {
            
            XmlHttp.open(method,url,true);
            XmlHttp.setRequestHeader("Content-Type",contentType);
            XmlHttp.setRequestHeader("Content-length", strParams.length);
            XmlHttp.setRequestHeader("Connection", "close");
            XmlHttp.onreadystatechange = callback;
            XmlHttp.send(strParams);
      }
      else
      {
            XmlHttp.open(method,url + "?" + strParams,true);
            XmlHttp.setRequestHeader("Content-Type",contentType);
            XmlHttp.setRequestHeader("Content-length", strParams.length);
            XmlHttp.setRequestHeader("Connection", "close");
            XmlHttp.onreadystatechange = callback;
            XmlHttp.send(null);
   
      }
   
  }
}
function getAddressValue(name) 
{ 
    var str=window.location.search; 
    //alert(str);
    if (str.indexOf(name)!=-1) 
    { 
        var pos_start=str.indexOf(name)+name.length+1; 
        var pos_end=str.indexOf("&",pos_start); 
        if (pos_end==-1) 
        { 
            return str.substring(pos_start); 
        } 
        else 
        { 
            return str.substring(pos_start,pos_end) 
        } 
    } 
    else 
    { 
        return "not find"; 
    } 
} 
function QuerySim(methodname)
{
    var querysim = new String();
	try
	{
		var querytarget = document.forms["form1"].elements["DeepThinkSearch"].options[document.forms["form1"].elements["DeepThinkSearch"].selectedIndex].text.toString();
		querysim ="http://"+ querytarget + ":9000/?method=" +methodname+"&target="+querytarget;
	}
	catch(failed)
	{
		querysim = "not find";
	}
    return querysim;
    
}
/*layout: display draw funcs
/*--------------------------------------------------------------------------*/

var downloadPopup = null;
var donwloadOpenSim = null;

function openDownLoadPage()
{    
   //alert(downloaduuid);
   downloadPopup= window.open("DownLoadDefault.aspx?DownLoadFile="+downloadFile+"&DownLoadGUID="+downloaduuid,"_self");

}
function openOpenSimDownLoadPage()
{
   var url = "http://" + getAddressValue("RegionIP") + ":9000?method=download_oar&region_id="+getAddressValue("RegionID");
   donwloadOpenSim = window.open(url,"_self");
}
//function sendOpenSimMessage(url, params)
//{
//    window.open(url + params,"_self");
//}
var waitBar = null;
function SetWaitform()
{
    var bar = document.getElementById("searchlist");
    waitBar = createBar(400,20,'white',1,'black','red',85,7,3,"");
    waitBar.showBar()
}
function SetStateInfo(html,IsWait)
{
    var state = document.getElementById("stateInfo");
    var bar = document.getElementById("progressBar");
    state.innerHTML = html;
    if(IsWait)
    {
        waitBar = createBar(400,20,'white',1,'black','red',85,7,3,"");
        waitBar.showBar()
    }
    else
    {
        bar.innerHTML = createProgressBar("DownLoaded ");
    }
}
function clearStateInfo()
{
    var state = document.getElementById("stateInfo");
    state.innerHTML = "Ready...";
    var bar = document.getElementById("progressBar");
    bar.innerHTML = "";
    var info = document.getElementById("info");
    info.innerHTML = "";//<img src=\"images\\earth.gif\" id=\"regionname\">" +getAddressValue(RegionName) ;
}
function setStateInfo(htmlinfo)
{
    var state = document.getElementById("stateInfo");
    state.innerHTML = htmlinfo;
}
function initializeState(sel)
{   
    switch(sel.name)
    {
        case "DownLoadTerrain":
        {
            SetStateInfo("Initializing Terrain Downloading...",true);
            
            break;
        }
        case "DownLoadOAR":
        {
            SetStateInfo("Initializing OAR Downloading...",true);
            
            break;
        }
        
    }
    
}
function initializeRegionTable()
{
    var div = document.getElementById("dvsearch");
    div.innerHTML = "";
    closeit();
    openDiv('load',5,'contentRight');
   
}
function checkStateInfo(xRows,state)
{
     if(state == "False")
     {
        alert(xRows[0].childNodes[2].firstChild.nodeValue);
     }
     else
     {
        setStateInfo(xRows[0].childNodes[0].firstChild.nodeValue);
        setTimeout('clearStateInfo()',1000);
     }
}
var downLoadName = new String();
var checkState = false;
var downloadFile = new String();
var downloaduuid = new String();

function checkStateLoop()
{
    
    if(checkState == false)
    {
        FillTerritory(document.forms["form1"].elements[downLoadName],document.forms["form1"].elements[downLoadName],FillLayout);
        setTimeout('checkStateLoop()',1000);
    }
    else
    {
        clearStateInfo();
        checkState = false;

        openDownLoadPage();
       
    }
}

function checkDownLoadState(xRows,State)
{
    var thePercent = xRows[0].childNodes[0].firstChild.nodeValue;
    
    var theText = xRows[1].childNodes[0].firstChild.nodeValue;
    
    downloadFile = xRows[2].childNodes[0].firstChild.nodeValue;
   
    beginBar("DownLoaded ",theText,thePercent);
                                             
    if(State == "FAILED")
    {
        checkState = false;
    }
    else
    {
        checkState = true; 
        
    }
}
function WebLogin(xRows,status,strMethod)
{
    if(status == "False")
    {
        alert(xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        InitMsgBox(strMethod,xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        
      //document.getElementById("contentRight").innerHTML = "<h1>Money Server-->Welcome to "+""+ "</h1>";
    }
    else
    {  //
        var username = xRows.getElementsByTagName('username')[0].childNodes[0].nodeValue;
        var userserver = xRows.getElementsByTagName('userserver')[0].childNodes[0].nodeValue;
        // alert(username);
        AccountLayout(username, userserver);
        
    }
}
function LoadcurrentPage(pageindex)
{
       // alert(pageindex);
       // document.getElementById("searchlist").innerHTML="";
       SetWaitform();
        var strParams = "form=form1&target=contentRight&method=LoadcurrentPage&seruris=&userID=&lastIndex=-1&currentPage=" + pageindex.toString();
       //  alert(strParams);

        var uri = "MoneyMonitor.aspx";
        ContentLoader(uri,FillLayout,"POST",strParams);   
}
function  WebGetBalance(xRows,strState,strMethod)
{
    if (strState == "False") 
    {
        if (ie) {
            
            InitMsgBox(strMethod, xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        }
        else {
            alert(xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        }
    }
    else {
        if (ie) {
            InitBalaceInfo(xRows.getElementsByTagName("userName")[0].childNodes[0].nodeValue, xRows.getElementsByTagName("balance")[0].childNodes[0].nodeValue);
        }
        else {
            alert(xRows.getElementsByTagName("userName")[0].childNodes[0].nodeValue + "\n" + xRows.getElementsByTagName("balance")[0].childNodes[0].nodeValue);
        }
    }
}
function WebGetTransactionNum(xRows,status,strMethod)
{
    if(status == "False")
    {
        alert(xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        document.getElementById("searchlist").innerHTML="";
        InitMsgBox(strMethod,xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
    }
    else
    {
        if(xRows.getElementsByTagName("number")[0].childNodes[0].nodeValue == 0)
        {
              document.getElementById("searchlist").innerHTML = "<br/><br/><br/><h1>User Transaction Records (0)</h1>";
        }
        else
        {
            var time = "&startTime=" + document.forms["form1"].elements["startTime"].value; //+ "-" +document.forms["form1"].elements["starthour"].options[document.forms["form1"].elements["starthour"].selectedIndex].text.toString() +"-"+ document.forms["form1"].elements["startmin"].options[document.forms["form1"].elements["startmin"].selectedIndex].text.toString()+"-"+document.forms["form1"].elements["startsec"].options[document.forms["form1"].elements["startsec"].selectedIndex].text.toString();
            time = time + "&endTime=" + document.forms["form1"].elements["endTime"].value;  //+ "-" +document.forms["form1"].elements["endhour"].options[document.forms["form1"].elements["endhour"].selectedIndex].text.toString() +"-" + document.forms["form1"].elements["endmin"].options[document.forms["form1"].elements["endmin"].selectedIndex].text.toString()+"-"+document.forms["form1"].elements["endsec"].options[document.forms["form1"].elements["endsec"].selectedIndex].text.toString();
            var strParams = "form=form1&target=contentRight&method=WebGetTransaction&seruris=&userID=&lastIndex=-1&currentPage=1&totalnum="+xRows.getElementsByTagName("number")[0].childNodes[0].nodeValue+time
           // alert(strParams);

            var uri = "MoneyMonitor.aspx";
        ContentLoader(uri,FillLayout,"POST",strParams);  
        }
        //alert(xRows.getElementsByTagName('number')[0].childNodes[0].nodeValue);
    }
}
function QueryLoad(xRows,status,strMethod)
{
    if(status == "False") {
        if (ie) {
            InitMsgBox("Query Transaction", "You hasn't login Money Server! You must login first!");
        }
        else {
            alert("You hasn't login Money Server!\n You must login first!"); 
        }
    }
    else
    {
        var user = xRows.getElementsByTagName('username')[0].childNodes[0].nodeValue;
        var userserver = xRows.getElementsByTagName('userserver')[0].childNodes[0].nodeValue;
    AccountLayout(user,userserver);
    }
}
function Webonload(xRows,status,strMethod)
{
    if(status == "False")
    {
        LoginLayout(xRows.getElementsByTagName('moneyserver')[0].childNodes[0].nodeValue, xRows.getElementsByTagName('userserver')[0].childNodes[0].nodeValue);
    }
    else
    {
        var user = xRows.getElementsByTagName('username')[0].childNodes[0].nodeValue;
        var userserver = xRows.getElementsByTagName('userserver')[0].childNodes[0].nodeValue;
    AccountLayout(user,userserver);
    }
}
function WebLogoff(xRows,status,strMethod)
{

   if(status == "False") {
       if (ie) {
           InitMsgBox("Log off", "You hasn't login Money Server! You must login first!");
       }
       else {
           alert("You hasn't login Money Server!\n You must login first!");
       }
    }
    else {
        if (ie) {
            InitInfoBox(xRows.getElementsByTagName('username')[0].childNodes[0].nodeValue, "Log off Money Server successful!");
        }
        else {
            alert(xRows.getElementsByTagName('username')[0].childNodes[0].nodeValue, "\nLog off Money Server successful!");
        }
    }
    LoginLayout(xRows.getElementsByTagName('moneyserver')[0].childNodes[0].nodeValue,xRows.getElementsByTagName('userserver')[0].childNodes[0].nodeValue);
    
      
}
function WebGetTransaction(xRows,status,strMethod)
{
    if(status == "False") {
        if (ie) {
           
            document.getElementById("searchlist").innerHTML = "";
            InitMsgBox(strMethod, xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        }
        else {
            alert(xRows.getElementsByTagName("message")[0].childNodes[0].nodeValue);
        }
        
      //document.getElementById("contentRight").innerHTML = "<h1>Money Server-->Welcome to "+""+ "</h1>";
    }
    else
    {
       
        document.getElementById("searchlist").innerHTML = xRows.getElementsByTagName('html')[0].childNodes[0].nodeValue
    } 
}
function loginhandler(xRows,status)
{
    if(status == "False")
    {
        var errortype = xRows.getElementsByTagName('error_type')[0].childNodes[0].nodeValue;
        switch(errortype)
        {
            case "unknown_user":
                {
                    document.getElementById('avatar_name').focus();
                    document.getElementById('avatar_name').value = "";
                    document.getElementById('avatarerror').innerHTML="<img class='img' src='images/error.png'/><font color='#CC0000'>"+xRows.getElementsByTagName('message')[0].childNodes[0].nodeValue+"</font>";
                    //InitMsgBox("dasf","asdf");
                   
                }
                break;
            case "verify_error":
                {
                    document.getElementById('verifynumber').focus();
                    document.getElementById('verifynumber').value = "";
                    document.getElementById("verifyerror").innerHTML="<img class='img' src='images/error.png'/><font color='#CC0000'>"+xRows.getElementsByTagName('message')[0].childNodes[0].nodeValue+"</font>";
                    // InitMsgBox("dasf","asdf");
                }
                break;
            default:
                {
                    document.getElementById('seruri').focus();
                    alert("User server address error:\n You must select the correct user server address or launch the user server and try again!");
                    InitMsgBox("get_user_by_name","User server address error:\n You must select the correct user server address or launch the user server and try again!");
 
                }
                break;
        }
        //alert(xRows.getElementsByTagName('message')[0].childNodes[0].nodeValue);
    }
    else
    {
        var userName = xRows.getElementsByTagName('username')[0].childNodes[0].nodeValue;
        var userID =  xRows.getElementsByTagName('userID')[0].childNodes[0].nodeValue;
        var moneyServer = xRows.getElementsByTagName('moneyserver')[0].childNodes[0].nodeValue;
        //alert("login:   "+userID + "money "+ moneyServer);
        //var strParams = "form=form1&target=contentRight&method=WebLogin&userid="+userID;
        //var uri = window.location.href;
        //ContentLoader(uri,FillLayout,"POST",strParams); 
        
        var strParams = "form=form1&target=contentRight&method=WebLogin&seruris="+moneyServer+"&userID="+userID +"&userName="+userName;

        var uri = "MoneyMonitor.aspx";
        ContentLoader(uri,FillLayout,"POST",strParams);  
        
    }
}
function GetBalance()
{
         var strParams = "form=form1&target=contentRight&method=WebGetBalance&seruris=&userID=";
                    
        var uri = "MoneyMonitor.aspx";
        ContentLoader(uri,FillLayout,"POST",strParams);     
}
var uploadstate = false; 
var uploaduuid = new String();
var uploadmethod = new String();
var uploadpath = new String();
function checkUpLoadState(xRows,method,state)
{
     //alert("hi");
    //alert(xRows[1].childNodes[0].firstChild.nodeValue.toString());
    //alert(state+" "+ xRows.length.toString()+" "+xRows[0].childNodes[0].firstChild.nodeValue+" "+xRows[1].childNodes[0].firstChild.nodeValue);
    var ipercent = xRows[2].childNodes[0].firstChild.nodeValue;

    var percentinfo = xRows[1].childNodes[0].firstChild.nodeValue;
   
    var uploadfile = xRows[0].childNodes[0].firstChild.nodeValue;
   
    uploadpath = xRows[3].childNodes[0].firstChild.nodeValue;
    
   // alert(ipercent + "|" + percentinfo + "|"+uploadfile+"|"+uploadpath);
    if(ipercent == "0")
    {
        SetStateInfo("Initializing  Uploading...",true);
    }
    else
    {
        SetStateInfo("Remote Service UpLoading ...",false);
        beginBar("UpLoaded " + uploadfile+"...",ipercent,percentinfo);
    }
       
    if(state == "FAILED")
    { 
        checkState = false;

    }
    else
    {
        uploadstate = true;
        FillTerritory(document.forms["form1"].elements["Terrain__Load"],document.forms["form1"].elements["Terrain__Load"],FillLayout);
    }
}
function uploadLoop()
{
    if(uploadstate == false)
    {
       // alert(document.forms["form1"].elements[uploadmethod].name);
        FillTerritory(document.forms["form1"].elements[uploadmethod],document.forms["form1"].elements[uploadmethod],FillLayout);
        setTimeout('uploadLoop()',1000);
    }
    else
    {
        clearStateInfo();
        uploadstate = false;
        //alert("Terrain__Load");
      
        
           
    }
}

function upLoadHandler(method,uuid)
{
    uploaduuid = uuid;
    uploadmethod = method;
    uploadLoop();    
}

function downLoadHandler(objDDL,xRows,State,strEName)
{
    var theText = xRows[0].childNodes[0].firstChild.nodeValue;  
                                       
    if(State == "FAILED")
    {
        clearStateInfo();
        objDDL.focus();
        objDDL.value = "http://...";
        alert(theText);
    }
    else
    {
        downLoadName = strEName;
        clearStateInfo();
        SetStateInfo("Remote Service DownLoading...",false);
        downloaduuid = theText;
       
        checkStateLoop();  
    }
    
}
function createRegionTable(xRows,State)
{
   
    var div = document.getElementById("dvsearch");
    closeDiv("load");

         
    
    for(i=0;i<xRows.length;i++)
    {
        var theText = xRows[i].childNodes[0].firstChild.nodeValue;                                         
                                             
        var theValue = xRows[i].childNodes[1].firstChild.nodeValue;
        
        if(State == "FAILED")
        {
            alert (theText);
            break;
        }
        
        var tableContent = "";
        
        tableContent += "<span><br /><br /> <br /></span>";
        tableContent += "<span><h2>"+"Region Name : "+theText.toString()+"("+theValue.toString()+")" +"</h2></span>";
        tableContent += "<table class = 'SearchTable'>";
        tableContent +=   "	<thead><tr style='vertical-align:middle;'><td class='top'>REGION NAME</td><td class='top'>REGION UUID</td><td class='top'>ALLOCATED RAM</td><td class='top'>SIMULATOR TEMPLATE</td><td class='top'>QUERY TIME</td></tr></thead>";
        tableContent += "<tbody><tr>";
        tableContent +=  "<td class='row'><a href=\"javascript:loadwindow(700,390,\'"+theValue.toString()+"\',\'"+theText.toString()+"\')\">"+theText.toString()+"</a></td><td class='row'>"+theValue.toString()+"</td><td class='row'>64MB</td><td class='row'>Standalone using SQLite</td><td class='row'>"+ new Date().toLocaleString() +"</td>";
        tableContent +=  "</tr></tbody>";
        tableContent +=  "</table>";   
              
        div.innerHTML += tableContent;
                 
    } 
}


/*layout: keypress funcs
/*--------------------------------------------------------------------------*/

function catch_keydown(sel)
{
	switch(event.keyCode)
	{
		case 13:
			//Enter;
			sel.options[sel.length] = new Option("","",false,true);
			event.returnValue = false;
			break;
		case 27:
			//Esc;
			alert("text:" + sel.options[sel.selectedIndex].text + ", value:" + sel.options[sel.selectedIndex].value + ";");
			event.returnValue = false;
			break;
		case 46:
			//Delete;
			if(confirm("delete current item?"))
			{
				sel.options[sel.selectedIndex] = null;
				if(sel.length>0)
				{
					sel.options[0].selected = true;
				}
			}
			event.returnValue = false;
			break;
		case 8:
			//Back Space
			var s = sel.options[sel.selectedIndex].text;
			sel.options[sel.selectedIndex].text = s.substr(0,s.length-1);
			event.returnValue = false;
			break;
	}
	
}
function catch_press(sel)
{
    var fldID = sel.id;
    //setTimeout("sel.focus();",1);
    sel.options[sel.selectedIndex].text = sel.options[sel.selectedIndex].text + String.fromCharCode(event.keyCode);
	event.returnValue = false;
}

//setInterval("aa.innerHTML=new Date().toLocaleString();",1000);


var LastLeftID = "";
function menuFix() {
	var obj = document.getElementById("nav").getElementsByTagName("li");
	
	for (var i=0; i<obj.length; i++) {
		obj[i].onmouseover=function() {
			this.className+=(this.className.length>0? " ": "") + "sfhover";
		}
		obj[i].onMouseDown=function() {
			this.className+=(this.className.length>0? " ": "") + "sfhover";
		}
		obj[i].onMouseUp=function() {
			this.className+=(this.className.length>0? " ": "") + "sfhover";
		}
		obj[i].onmouseout=function() {
			this.className=this.className.replace(new RegExp("( ?|^)sfhover\\b"), "");
		}
	}
}
function DoMenu(emid)
{
	var obj = document.getElementById(emid);	
	obj.className = (obj.className.toLowerCase() == "expanded"?"collapsed":"expanded");
	if((LastLeftID!="")&&(emid!=LastLeftID))	//关闭上一个Menu
	{
		document.getElementById(LastLeftID).className = "collapsed";
	}
	LastLeftID = emid;
}
function GetMenuID()
{
	var MenuID="";
	var _paramStr = new String(window.location.href);
	var _sharpPos = _paramStr.indexOf("#");
	
	if (_sharpPos >= 0 && _sharpPos < _paramStr.length - 1)
	{
		_paramStr = _paramStr.substring(_sharpPos + 1, _paramStr.length);
	}
	else
	{
		_paramStr = "";
	}
	
	if (_paramStr.length > 0)
	{
		var _paramArr = _paramStr.split("&");
		if (_paramArr.length>0)
		{
			var _paramKeyVal = _paramArr[0].split("=");
			if (_paramKeyVal.length>0)
			{
				MenuID = _paramKeyVal[1];
			}
		}
		/*
		if (_paramArr.length>0)
		{
			var _arr = new Array(_paramArr.length);
		}
		
		//取所有#后面的，菜单只需用到Menu
		//for (var i = 0; i < _paramArr.length; i++)
		{
			var _paramKeyVal = _paramArr[i].split('=');
			
			if (_paramKeyVal.length>0)
			{
				_arr[_paramKeyVal[0]] = _paramKeyVal[1];
			}		
		}
		*/
	}
	
	if(MenuID!="")
	{
		DoMenu(MenuID)
	}
}
//GetMenuID();	//*这两个function的顺序要注意一下，不然在Firefox里GetMenuID()不起效果
//menuFix();
//////////////////////////////////////////////////////////////////////////////////////////////////
//
//windows on load
//////////////////////////////////////////////////////////////////////////////////////////////////
function onloadlogin()
{
  var strParams = "form=form1&target=contentRight&method=onload";
  var uri = "MoneyMonitor.aspx";
  ContentLoader(uri,FillLayout,"POST",strParams);  
  
}
function QueryTransaction()
{
  var strParams = "form=form1&target=contentRight&method=queryTransaction";
  var uri = "MoneyMonitor.aspx";
  ContentLoader(uri,FillLayout,"POST",strParams);  
}
function Logoff()
{
    var strParams = "form=form1&target=contentRight&method=Logoff";
     var uri = "MoneyMonitor.aspx";
  ContentLoader(uri,FillLayout,"POST",strParams);   
}

window.onload = function()
{
//LoginLayout();
    onloadlogin();
  //  FillTerritory(document.getElementById("contentRight"),document.getElementById("contentRight"),FillLayout,"POST");   
}
window.onunload  = function()
{
if (confirm("Do you want to log off money server") ==true)
{
    Logoff();
}
else
{
//return;
}
}
function LoginLayout(moneyserver,userserver)
{
    var titleContent = "";
    titleContent = titleContent +"<h1>Money Server</h1><h2>You must fill your money server accout info into the login form as well as the verify value,click the image you can change the verify image.</h2>";
    titleContent = titleContent +"<table id ='dtable' align='center' style='position:relative; border: 0px dotted #dfdfdf; left : 0px; top:0px; width: 100% ;height:50%' ><tbody>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +"<td class='rowalt'>Money URI :</td><td class='row' style='width: 248px'><select  id = 'seruri'  name = 'seruri' title = 'Money server uri address' onkeydown='catch_keydown(this);' onkeypress='catch_press(this);'  style='font-size:12px; width: 244px;' >";
    titleContent = titleContent + "<option>" + moneyserver + "</option> </select></td>";
    titleContent = titleContent +"<td ><font color='#555555'>You can select a user server ip to login and communicate with money server</font></td>";
    titleContent = titleContent +"</tr>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +"<td class='rowalt'>User Server URI :</td><td class='row' style='width: 248px'><select  id = 'useruri'  name = 'useruri' title = 'Click the select and edit the ip address' onkeydown='catch_keydown(this);' onkeypress='catch_press(this);'  style='font-size:12px; width: 244px;' >";
    titleContent = titleContent + "<option>" + userserver + "</option></select></td>";
    titleContent = titleContent +"<td ><font color='#555555'>You can select a user server ip to login or you can edit the server uri manually </font></td>";
    titleContent = titleContent +"</tr>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +"<td class='rowalt'>Avater Name :</td><td class='row' style='width: 248px'><input type='text' id='avatar_name' name='avatar_name' size='35' value='' title ='(firsname lastname):avater_name' onblur = \" document.getElementById('avatarerror').innerHTML=''\"/></td>";
    titleContent = titleContent +"<td  id='avatarerror'></td>";
    titleContent = titleContent +"</tr>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +"<td class='rowalt'>Pass Word :</td><td class='row' style='width: 248px'><input type='password' id='password' name='password' size='35' value=''title ='admin password'onblur = \" document.getElementById('passworderror').innerHTML=''\" /></td>";
    titleContent = titleContent +"<td id='passworderror'></td>";
    titleContent = titleContent +"</tr>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +"<td class='rowalt'>Verify Value :</td><td class='row' style='width: 248px'><input type='text' id='verifynumber' name='verifynumber' maxlength= '6' size ='35' title ='input the string below' onblur=\" document.getElementById('verifyerror').innerHTML=''\"/></td>";
    titleContent = titleContent +"<td  id='verifyerror'></td>";
    titleContent = titleContent +"</tr>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +" <td class='row'><font color='#CCC'> </font></td><td class='row' style='width: 248px'><img id='cknimg' name = 'cknimg' src= 'VerifyCode.aspx?' alt='Click here to change the image' style='cursor:pointer;' onclick=\"this.src= this.src +'?'\" /></td>";
    titleContent = titleContent +"</tr>";
    titleContent = titleContent +"<tr>";
    titleContent = titleContent +"  <td class='row'><font color='#CCC'> </font></td><td class='row' style='width: 248px'><input id='get_user_by_name' name ='get_user_by_name' type='button'  value='Login Money Server' style='cursor:pointer; width: 270px;' onclick=\"FillTerritory(document.form1.get_user_by_name,document.form1.get_user_by_name,FillLayout,'POST')\" />";
    titleContent = titleContent +"</tr></tbody></table>";
    document.getElementById("contentRight").innerHTML = titleContent;
}
function initialLayout()
{
   // document.getElementById("searchlist").innerHTML ="";
   // openDiv('load',5,'contentRight');
}
function AccountLayout(user,userserver)
{
   
    var titleContent = "";
    titleContent = titleContent + "<h1> Hello! " + user + " (" + userserver + ") --- Welcome to Money Server</h1><h2>You must fill your money server transaction search into the search form ,you can selcet the start time and end time!</h2>";
    titleContent = titleContent +"<table id ='dtable' align='center' style='position:relative; border: 0px dotted #dfdfdf; left : 0px; top:0px; width: 100% ;height:10%' ><tbody>";
    titleContent = titleContent + "<thead><tr style='vertical-align:middle;'><td class='top'>Start Time</td><td class='top' >End Time</td><td class='top'> Search Money Server</td><tr></thead>";
    titleContent = titleContent +"<tbody> <tr>";
    titleContent = titleContent + "<td class='rowalt'>DATE : <input type='text' name='startTime' id='startTime' title='click here and select start time date' onclick=\"WdatePicker({startDate:'%y-%M-01-00-00-00',dateFmt:'yyyy-MM-dd-HH-mm-ss',alwaysUseStartDate:true})\" value='2009-04-01-00-00-00'></input></td>";
    titleContent = titleContent + "<td class='rowalt'>DATE : <input type='text' name='endTime' id='endTime' title='click here and select end time date' onclick=\"WdatePicker({startDate:'%y-%M-%d-00-00-00',dateFmt:'yyyy-MM-dd-HH-mm-ss',alwaysUseStartDate:true})\" value='2009-05-30-00-00-00'></input></td>";
    titleContent = titleContent +"<td  class='rowalt'><input id='WebGetTransactionNum' name ='WebGetTransactionNum' type='button'  value='Search Money Server' style='cursor:pointer; width: 270px;' onclick=\"SetWaitform();FillTerritory(document.form1.WebGetTransactionNum,document.form1.WebGetTransactionNum,FillLayout,\'POST\')\"></td>";
    titleContent = titleContent +"</tr> </tbody></table>";
    titleContent = titleContent + "<div id='searchlist'></div>";
    document.getElementById("contentRight").innerHTML = titleContent;
      
    
}
